/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SysInfoView.java
 *
 * Created on 14.11.2009, 23:27:31
 */
package ru.roman.greet.gui.pane.sysinfo;


import javax.swing.*;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import java.awt.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Enumeration;
import java.util.Properties;

/**
 *
 * @author Roman
 */
public class SysInfoView extends javax.swing.JFrame {

    /** Creates new form SysInfoView */
    public SysInfoView() {
        initComponents();
        paintHtmlText();
    }

    void paintHtmlText() {

        JEditorPane pane = new JEditorPane();
        pane.setEditable(true);

        HTMLEditorKit kit = new HTMLEditorKit();
        pane.setEditorKit(kit);

        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule("body {color:#000; font-family:times; margin: 4px; }");
        styleSheet.addRule("h1 {color: blue;}");
        styleSheet.addRule("h2 {color: #ff0000;}");
        styleSheet.addRule("pre {font : 10px monaco; color : black; background-color : #fafafa; }");


        StringBuilder html = new StringBuilder();
        html.append("<html>\n");
        html.append("<body>\n");
        html.append("<h1>System Properties</h1>\n");
        html.append("<h2>Inet Address</h2>\n");
        html.append("<p>InetAddress.LocalHost = ");
        try {
            html.append(InetAddress.getLocalHost());
        } catch (UnknownHostException e) {
            throw new RuntimeException(e);
        }
        html.append("</p>\n");
        html.append("<h2>System Properties</h2>\n");

        Properties prop = System.getProperties();
        Enumeration propNames = prop.propertyNames();
        String somePropName;

        for (;propNames.hasMoreElements();) {
            somePropName = (String)propNames.nextElement();
            html.append("<p>");
            html.append(somePropName);
            html.append(" = ");
            html.append(prop.getProperty(somePropName));
            html.append("</p>\n");
        }

        Document doc = kit.createDefaultDocument();
        pane.setDocument(doc);
        pane.setText(html.toString());

        jScrollPane1.setViewportView(pane);
        this.setSize(new Dimension(600, 600));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
